### 관리자 로그인
POST http://localhost:8001/web/members/login
Content-Type: application/json

{
  "name": "master",
  "password": "!password12"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### 게임 생성
POST http://localhost:8001/web/games/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "type": "baseball",
  "title": "한국시리즈 1차전",
  "home": "기아타이거즈",
  "away": "두산베어스",
  "place": "광주-기아 챔피언스필드",
  "startedAt": "2024-03-02T17:00:00"
}

### 게임 조회
GET http://localhost:8001/web/games/1
Authorization: Bearer {{accessToken}}

### 게임 수정
PATCH http://localhost:8001/web/games/update/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "type": "baseball",
  "title": "한국시리즈 1차전",
  "home": "기아타이거즈",
  "away": "두산베어스",
  "place": "광주-기아 챔피언스필드",
  "startedAt": "2024-03-02T17:00:00"
}

### 게임 삭제
PATCH http://localhost:8001/web/games/delete/1
Authorization: Bearer {{accessToken}}

### 게임 복구
PATCH http://localhost:8001/web/games/restore/1
Authorization: Bearer {{accessToken}}
