### 회원가입
POST http://localhost:8001/web/members/signup
Content-Type: application/json

{
  "name": "name",
  "password": "password",
  "email": "email",
  "nickname": "nickname"
}

### 비밀번호 검증
POST http://localhost:8001/web/members/validate
Content-Type: application/json

{
  "name": "name",
  "password": "password"
}
