spring:
  application:
    name: web-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

server:
  port: 9001

jwt:
  secret-key: ${JWT_SECRET_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  token:
    access-expiration-time: ${JWT_TOKEN_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_TOKEN_REFRESH_EXPIRATION_TIME}
