spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/web/members/signup,/web/members/login,/web/members/reissue
          filters:
            - RewritePath=/web/(?<segment>.*),/v1/web/$\{segment}
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/web/**
          filters:
            - RewritePath=/web/(?<segment>.*),/v1/web/$\{segment}
            - AuthorizationHeaderFilter
        - id: flow-service
          uri: lb://flow-service
          predicates:
            - Path=/flow/**
          filters:
            - RewritePath=/flow/(?<segment>.*),/v1/flow/$\{segment}
            - AuthorizationHeaderFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8001

jwt:
  secret-key: ${JWT_SECRET_KEY}
