### 관리자 로그인
POST http://localhost:8001/web/members/login
Content-Type: application/json

{
  "name": "master",
  "password": "!password12"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### 등급 생성
POST http://localhost:8001/web/grades/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "placeId": 10,
  "name": "내야석"
}

### 등급 수정
PATCH http://localhost:8001/web/grades/update/148
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "placeId": 10,
  "name": "내야석"
}

### 등급 삭제
PATCH http://localhost:8001/web/grades/delete/148
Authorization: Bearer {{accessToken}}

### 등급 복구
PATCH http://localhost:8001/web/grades/restore/148
Authorization: Bearer {{accessToken}}
