### 관리자 로그인
POST http://localhost:8001/web/members/login
Content-Type: application/json

{
  "name": "master",
  "password": "!password12"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### 장소 생성
POST http://localhost:8001/web/places/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "다저스타디움"
}

### 장소 수정
PATCH http://localhost:8001/web/places/update/10
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "오라클파크"
}

### 장소 삭제
PATCH http://localhost:8001/web/places/delete/10
Authorization: Bearer {{accessToken}}

### 장소 복구
PATCH http://localhost:8001/web/places/restore/10
Authorization: Bearer {{accessToken}}
