### 관리자 로그인
POST http://localhost:8001/web/members/login
Content-Type: application/json

{
  "name": "master",
  "password": "!password12"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### 티켓 생성
POST http://localhost:8001/web/tickets/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "gameId": 1,
  "gradeId": 1,
  "quantity": 2000000,
  "price": 18000
}
