### 관리자 로그인
POST http://localhost:8001/web/members/login
Content-Type: application/json

{
  "name": "master",
  "password": "!password12"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### 티켓 생성
POST http://localhost:8001/web/tickets/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "gameId": 1,
  "gradeId": 1,
  "quantity": 2000,
  "price": 18000
}

### 대기열 탐색
GET http://localhost:8001/flow/1
Authorization: Bearer {{accessToken}}

> {%
    client.global.set('cookie', response.headers.valueOf('Set-Cookie'));
%}

### 티켓 예매
POST http://localhost:8001/web/tickets/reserve
Authorization: Bearer {{accessToken}}
Cookie: {{cookie}}
Content-Type: application/json

{
  "gameId": 1,
  "ticketId": 1
}

### 티켓 결제
POST http://localhost:8001/web/tickets/payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "method": "card",
  "amount": 18000
}

### 티켓 취소
POST http://localhost:8001/web/tickets/cancel/1
Authorization: Bearer {{accessToken}}
