spring:
  application:
    name: flow-service
  data:
    redis:
      host: 127.0.0.1
      port: 6380

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

server:
  port: 9002

scheduler:
  enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
