spring:
  application:
    name: flow-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 9002
