services:
  web-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  flow-redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data2:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
  redis-data2:  # 새로운 볼륨 정의
